name: Daniel Hazard
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21119
title: Daniel Hazard
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#271919'
    - '#c39395'
    - '#7e5856'
    - '#eee9e6'
    - '#f2bcc3'
  brandStrength: 0
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
