name: Daniel Hazard
favicon: null
layout_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#271919'
    - '#c39395'
    - '#7e5856'
    - '#eee9e6'
    - '#f2bcc3'
  brandStrength: 0.5
  lightness: null
  saturation: null
  rhythmicContrast: null
purpose: []
